### ISSUE TITLE
Reloading Account

### ISSUE THREAD

**Issue by Swegmunsta** [atomizer/muledump#76] opened 2015-07-22 19:22 UTC
I open up my muledump and it's showing my account from a long time ago, and my characters and vault aren't updated. I tried reloading it many times and I also have the newest version of muledump. Solution?

**Comment by Nightfirecat** [comment] 2015-07-22 19:41
How recently have you logged into the game using this account?

**Comment by GhostMaree** [comment] 2015-07-22 20:03
your account is migrated?

**Comment by Swegmunsta** [comment] 2015-07-23 01:39
I've been online a lot for a couple days @Nightfirecat.  I think my account is migrated is there a way to check? @GhostMaree

**Comment by BlackRayquaza** [comment] 2015-07-24 19:43
Are you sure that its the right account?

**Comment by Nightfirecat** [comment] 2015-09-26 08:19
@Swegmunsta, Are you certain that the email/password in your `accounts.js` match what you use to log in, *exactly*? That is, can you copy the email/password from your `accounts.js` to the game and have them work successfully?

**Comment by ManWithBear** [comment] 2015-09-27 19:07
I have same issue.
Last login was 2 days ago. Muledump show my account state when i was 58 star, now i'm 64. I got 59 star 5 month ago.
Now I login in game and walk to nexus with every character. And no changes in muledump.
Using Steam version.

**Comment by Nightfirecat** [comment] 2015-09-28 00:13
Can you try clearing your browser cache and reloading muledump?

**Comment by ManWithBear** [comment] 2015-09-28 00:24
It's not looks like cache problem, cauz today I first time used muledump.
I delete all cache that reference to rotmg, still 5 month old data.

**Comment by Nightfirecat** [comment] 2015-09-28 03:02
Ah, ok. @atomizer, I wonder if this may have been caused by account migration somehow? Seems like it only affects some people.

**Comment by ManWithBear** [comment] 2015-11-14 16:50
Test last version. Still old data.

**Comment by atomizer** [comment] 2015-11-22 10:24
The reason for this is that web accounts that were created through Steam got detached during migration and are now separate "clones". To get up to date information in muledump, follow the [Steam tutorial](https://github.com/atomizer/muledump/wiki/Steam-Tutorial).

**Comment by ManWithBear** [comment] 2015-11-22 14:53
Em, I don't have web account. I got access to my account by this tutorial. So problem not in web account.

**Comment by atomizer** [comment] 2015-11-22 14:58
Ok, back to square one.

**Comment by BlackRayquaza** [comment] 2015-11-25 02:53
@ManWithBear But can you access your steam account through web?

**Comment by ManWithBear** [comment] 2015-11-25 17:15
@BlackRayquaza no, I dont have web account. Or here anyway to use steam credentials for login in browser?

**Comment by ManWithBear** [comment] 2015-12-02 00:24
It's looks like I fix it. 
In realmapi.js change base url to just right one:
var BASEURL = 'https://realmofthemadgodhrd.appspot.com/'

**Comment by ManWithBear** [comment] 2015-12-02 00:25
Now I see my actual characters.

**Comment by Nightfirecat** [comment] 2015-12-02 03:47
Hm, that makes sense. I'll see about getting a page on the wiki or a note into the README addressing that. Glad it finally works for you!

**Comment by Nightfirecat** [comment] 2015-12-05 04:32
Created [a new section on the Troubleshooting wiki page](https://github.com/atomizer/muledump/wiki/Troubleshooting#my-account-is-showing-old-data-and-does-not-update) for this issue.
@atomizer, this issue should be resolved with that.

**Closed** 2015-12-05 11:24 UTC
