### ISSUE TITLE
Doesnt work with kabam.com accounts

### ISSUE THREAD

**Issue by syx11** [atomizer/muledump#70] opened 2015-05-17 14:19 UTC
I can get it to work on realmofthemadgod.com accounts however accounts connected to kabam do not work. Help?

**Comment by atomizer** [comment] 2015-05-17 20:48
Sorry, kabam accounts are not supported at the moment. Duplicate of #58. There is no progress on this at the moment, if you're willing to research what the process of logging into a kabam account programmatically, feel free to share any details in that issue.

**Closed by atomizer** 2015-05-17 20:48 UTC

**Comment by syx11** [comment] 2015-05-17 21:08
oh ok thanks
