### ISSUE TITLE
Load Data Server Error

### ISSUE THREAD

**Issue by Null0Zer0** [atomizer/muledump#154] opened 2017-09-01 12:43 UTC
Whenever i try and reload a character of mine it will give me this error;

loading data
server error
full response:{"count":0,"created":"2017-09-01T12:38:52Z","lang":"en-US","results":null}

If i reload it enough it will work, but that is after like 12 times i reload each account in the dump...
Anyone got some help for me?
Thanks in advance-

**Comment by tischepe** [comment] 2017-09-01 12:46
Duplicate of https://github.com/atomizer/muledump/issues/148

**Comment by Null0Zer0** [comment] 2017-09-01 12:48
Thanks @tischepe i'll take a look at that!

**Closed** 2017-09-01 13:17 UTC
