### ISSUE TITLE
One click login.

### ISSUE THREAD

**Issue by silentWizz** [atomizer/muledump#91] opened 2016-01-23 16:23 UTC
Hello. I'm having trouble using Flash Projector to open up a custom client for RotMG. I have downloaded the newest version and installed AutoIt as well.

When I try it with Chrome it loads my mules just fine but when I edit out ShellExecute("http://www.realmofthemadgod.com/") to ShellExecute('C:\Users\User\Desktop\client-mod.swf') it only opens the .swf file but doesn't log in my mule.

Am I missing something here? Can someone please post a working mulelogin.au3 which uses flash projector?

Thanks!

**Comment by Nightfirecat** [comment] 2016-01-23 22:49
Your client may be reading from a different Flash local cache directory. You will have to add that to the list of directories written to by AutoIt.

**Comment by silentWizz** [comment] 2016-01-27 09:14
Sorry for being a total noob but how exactly can I do that?

**Comment by Nightfirecat** [comment] 2016-01-28 03:12
Not a problem, but actually, based on the discussion in #90, it sounds like there's some other issue going on, not an issue with the code. If we find out, I'll post that here as well.

**Comment by atomizer** [comment] 2016-07-15 17:26
duplicate of #90

**Closed by atomizer** 2016-07-15 17:26 UTC
